# Generated by Django 2.2.8 on 2019-12-11 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practica_07', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musico',
            name='dni',
            field=models.AutoField(max_length=10, primary_key=True, serialize=False),
        ),
    ]
