# Generated by Django 2.2.8 on 2019-12-11 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practica_07', '0002_auto_20191211_1708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musico',
            name='dni',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
